"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import "./factory.css";

type LinkItem={id:string;provider:string;link_type:string;label:string;url:string;status:string;verified_at?:string|null};
type BusinessItem={business_key:string;business_name:string;relation_role:string;control_id?:string|null};
type Product={id:string;name:string;slug:string;product_type:string;description?:string|null;status:string;preview_url?:string|null;production_url?:string|null;thumbnail_url?:string|null;links:LinkItem[];businesses:BusinessItem[];asset_count:number;memory_count:number};

type View="preview"|"library"|"businesses"|"memory";
const PROVIDERS=["chatgpt","drive","github","vercel","supabase","control_central","external"];

export default function FactoryClient(){
 const [products,setProducts]=useState<Product[]>([]); const [activeId,setActiveId]=useState<string|null>(null); const [view,setView]=useState<View>("library"); const [loading,setLoading]=useState(true); const [notice,setNotice]=useState(""); const [showCreate,setShowCreate]=useState(false); const [showLink,setShowLink]=useState(false); const [showBusiness,setShowBusiness]=useState(false); const [showMemory,setShowMemory]=useState(false); const [device,setDevice]=useState<"desktop"|"mobile">("desktop");
 const active=useMemo(()=>products.find(p=>p.id===activeId)??products[0]??null,[products,activeId]);
 const previewLink=active?.links.find(l=>l.provider==="vercel"&&l.status==="verified"&&(l.link_type.includes("preview")||l.link_type.includes("production")))?.url || active?.preview_url || active?.production_url || null;

 async function reload(){setLoading(true); const r=await fetch("/api/factory",{cache:"no-store"}); const j=await r.json(); if(r.ok){setProducts(j.products||[]); if(!activeId&&j.products?.[0])setActiveId(j.products[0].id)} else setNotice(j.error||"No se pudo cargar Factory"); setLoading(false)}
 useEffect(()=>{reload()},[]);
 async function post(payload:Record<string,unknown>){setNotice(""); const r=await fetch("/api/factory",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}); const j=await r.json(); if(!r.ok){setNotice(j.error||"Error");return false} await reload(); return true}
 async function createProduct(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await post({action:"create_product",name:f.get("name"),product_type:f.get("type"),description:f.get("description")})){setShowCreate(false);e.currentTarget.reset()}}
 async function addLink(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!active)return;const f=new FormData(e.currentTarget);if(await post({action:"add_link",product_id:active.id,provider:f.get("provider"),link_type:f.get("link_type"),label:f.get("label"),url:f.get("url")})){setShowLink(false);e.currentTarget.reset()}}
 async function addBusiness(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!active)return;const f=new FormData(e.currentTarget);if(await post({action:"add_business",product_id:active.id,business_name:f.get("business_name"),relation_role:f.get("role")})){setShowBusiness(false);e.currentTarget.reset()}}
 async function addMemory(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!active)return;const f=new FormData(e.currentTarget);if(await post({action:"add_memory",product_id:active.id,title:f.get("title"),memory_type:f.get("memory_type"),summary:f.get("summary"),source_url:f.get("source_url")})){setShowMemory(false);e.currentTarget.reset()}}

 return <div className="factory-shell">
  <aside className="factory-rail"><div className="factory-logo">LF</div>{([['preview','◫','Preview'],['library','⌗','Biblioteca'],['businesses','◉','Negocios'],['memory','⌘','Memoria']] as [View,string,string][]).map(([k,i,l])=><button key={k} className={view===k?'active':''} onClick={()=>setView(k)}><span>{i}</span><small>{l}</small></button>)}</aside>
  <main className="factory-main">
   <header className="factory-top"><div><b>LINK Factory</b><span>Creative Operating System</span></div><div className="top-actions"><button onClick={()=>setShowCreate(true)}>＋ Crear producto</button></div></header>
   {notice&&<div className="notice">{notice}</div>}
   <section className="factory-page">
    {loading?<div className="empty">Cargando biblioteca real…</div>:products.length===0?<div className="empty-state"><span>Biblioteca vacía</span><h1>No hay productos fake.</h1><p>Crea el primer producto gráfico. Los links aparecerán desconectados hasta que existan y sean verificados.</p><button onClick={()=>setShowCreate(true)}>Crear primer producto</button></div>:<>
      {view==="library"&&<><div className="hero"><div><small>01 / Biblioteca</small><h1>Productos,<br/>no carpetas.</h1></div><p>Cada ficha une un producto gráfico con sus negocios, memoria y enlaces reales al resto del ecosistema.</p></div><div className="product-grid">{products.map(p=><button className={`product-card ${active?.id===p.id?'selected':''}`} key={p.id} onClick={()=>{setActiveId(p.id);setView('preview')}}><div className="product-cover"><span>{p.product_type}</span><h2>{p.name}</h2></div><div className="product-meta"><b>{p.name}</b><span>{p.links.length} links · {p.businesses.length} negocios · {p.memory_count} memorias</span></div></button>)}</div></>}
      {view==="preview"&&active&&<><div className="hero compact"><div><small>02 / Producto activo</small><h1>{active.name}</h1></div><p>{active.description||"Sin descripción todavía."}</p></div><div className="preview-layout"><div className="browser"><div className="browser-bar"><span>←</span><span>→</span><span>↻</span><div className="address">{previewLink||"Sin preview conectada"}</div><button onClick={()=>setDevice('desktop')} className={device==='desktop'?'active':''}>Desktop</button><button onClick={()=>setDevice('mobile')} className={device==='mobile'?'active':''}>Mobile</button></div><div className="browser-stage">{previewLink?<iframe className={device==='mobile'?'mobile':''} src={previewLink} title={active.name}/>:<div className="no-preview"><b>Preview no conectada</b><span>Agrega un link Vercel y verifícalo para navegar la experiencia aquí.</span><button onClick={()=>setShowLink(true)}>＋ Conectar preview</button></div>}</div></div><aside className="detail-stack"><div className="detail-card"><small>Estado</small><h3>{active.status}</h3><div className="chips"><span>{active.product_type}</span><span>{active.businesses.length} negocios</span></div></div><div className="detail-card"><div className="card-head"><small>Biblioteca de links</small><button onClick={()=>setShowLink(true)}>＋</button></div>{active.links.length===0?<p>Sin links todavía.</p>:active.links.map(l=><div className="link-row" key={l.id}><div><b>{l.label}</b><span>{l.provider} · {l.status}</span></div>{l.status==='verified'?<a href={l.url} target="_blank" rel="noreferrer">Abrir ↗</a>:<button onClick={()=>post({action:'verify_link',link_id:l.id})}>Verificar</button>}</div>)}</div><div className="detail-card"><div className="card-head"><small>Negocios relacionados</small><button onClick={()=>setShowBusiness(true)}>＋</button></div>{active.businesses.length===0?<p>Sin negocios asociados.</p>:active.businesses.map(b=><div className="link-row" key={`${b.business_key}-${b.relation_role}`}><div><b>{b.business_name}</b><span>{b.relation_role}</span></div></div>)}</div><div className="detail-card"><div className="card-head"><small>Memoria</small><button onClick={()=>setShowMemory(true)}>＋</button></div><h3>{active.memory_count} registros</h3><p>La memoria se referencia; no se duplica el archivo fuente.</p></div></aside></div></>}
      {view==="businesses"&&<><div className="hero"><div><small>03 / Negocios</small><h1>Relaciones<br/>reales.</h1></div><p>Un producto puede servir a varios negocios y un negocio puede tener muchos productos.</p></div><div className="business-grid">{Array.from(new Map(products.flatMap(p=>p.businesses.map(b=>[b.business_key,b])).values())).map(b=><div className="business-card" key={b.business_key}><small>{b.relation_role}</small><h2>{b.business_name}</h2><span>{products.filter(p=>p.businesses.some(x=>x.business_key===b.business_key)).length} productos asociados</span></div>)}</div></>}
      {view==="memory"&&<><div className="hero"><div><small>04 / Memoria</small><h1>Todo queda<br/>ligado.</h1></div><p>La app muestra únicamente conteos y referencias existentes en Supabase. Nada inventado.</p></div><div className="memory-grid">{products.map(p=><div className="memory-card" key={p.id}><small>{p.product_type}</small><h2>{p.name}</h2><div><b>{p.memory_count}</b><span> memorias</span></div><div><b>{p.asset_count}</b><span> activos</span></div><div><b>{p.links.filter(l=>l.status==='verified').length}</b><span> links verificados</span></div></div>)}</div></>}
    </>}
   </section>
  </main>
  {showCreate&&<Modal title="Crear producto" close={()=>setShowCreate(false)}><form onSubmit={createProduct}><input name="name" placeholder="Nombre" required/><select name="type" defaultValue="website"><option value="website">Website</option><option value="app">App</option><option value="campaign">Campaña</option><option value="catalog">Catálogo</option><option value="graphic">Producto gráfico</option></select><textarea name="description" placeholder="Descripción"/><button className="submit">Crear ficha</button></form></Modal>}
  {showLink&&active&&<Modal title="Conectar link" close={()=>setShowLink(false)}><form onSubmit={addLink}><select name="provider">{PROVIDERS.map(p=><option key={p}>{p}</option>)}</select><input name="link_type" placeholder="Tipo: project, drive_folder, repo, preview…" required/><input name="label" placeholder="Etiqueta" required/><input name="url" type="url" placeholder="https://…" required/><p className="form-note">Ley anti-fake: quedará “unverified” hasta comprobar el destino.</p><button className="submit">Guardar link</button></form></Modal>}
  {showBusiness&&active&&<Modal title="Asociar negocio" close={()=>setShowBusiness(false)}><form onSubmit={addBusiness}><input name="business_name" placeholder="Nombre del negocio" required/><select name="role"><option value="owner">Principal</option><option value="channel">Canal</option><option value="producer">Productor</option><option value="partner">Partner</option></select><button className="submit">Asociar</button></form></Modal>}
  {showMemory&&active&&<Modal title="Añadir memoria" close={()=>setShowMemory(false)}><form onSubmit={addMemory}><input name="title" placeholder="Título" required/><select name="memory_type"><option value="context">Contexto</option><option value="decision">Decisión</option><option value="brief">Brief</option><option value="learning">Aprendizaje</option></select><textarea name="summary" placeholder="Resumen"/><input name="source_url" type="url" placeholder="Fuente opcional https://…"/><button className="submit">Registrar memoria</button></form></Modal>}
 </div>
}

function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><div className="modal"><div className="modal-head"><h3>{title}</h3><button onClick={close}>×</button></div>{children}</div></div>}
