"use client";
import {useCallback,useEffect,useMemo,useState} from "react";

type Client={id:string;name:string;stage?:string;plan?:string;monthlyValue?:number;effectiveFrom?:string;gestureCount?:number;calendar?:{id:string;calendar_name?:string;status:string;google_calendar_id?:string|null;timezone:string;last_synced_at?:string|null};strategy?:any;cycle?:any};
type Gesture={id:string;client_id:string;title:string;description?:string|null;status:string;starts_at:string;ends_at?:string|null;recurrence_rule?:string|null;sync_status:string;priority:number;source:string};
type Summary={clients:Client[];gestures:Gesture[];operational:any;services:any[];recentEvents:any[];readiness:any};
type Occ={key:string;gesture:Gesture;date:Date};
type CalMode="Mes"|"Día"|"Año"|"Lista";
const NAV=["Inicio","Clientes","Gestos","Calendario","Actividad","Integraciones"] as const; type View=typeof NAV[number];
const DAYMAP:{[k:string]:number}={SU:0,MO:1,TU:2,WE:3,TH:4,FR:5,SA:6};

export default function LinkControlDashboardV6(){const[view,setView]=useState<View>("Inicio"),[data,setData]=useState<Summary|null>(null),[selected,setSelected]=useState<string|null>(null),[month,setMonth]=useState(new Date(2026,8,1)),[modal,setModal]=useState(false),[error,setError]=useState("");const load=useCallback(async()=>{const r=await fetch('/api/system-summary',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'No se pudo cargar');setData(j)},[]);useEffect(()=>{load().catch(e=>setError(e.message))},[load]);if(!data)return <div className="v6loading">Cargando CONTROL CENTRAL…</div>;const client=data.clients.find(c=>c.id===selected)||null;const canRegister=view!=="Integraciones"&&view!=="Actividad";return <div className="v6shell"><aside className="v6side"><b>LINK CONTROL CENTRAL</b>{NAV.map(n=><button key={n} className={view===n?'on':''} onClick={()=>{setView(n);setSelected(null)}}>{n}</button>)}</aside><main className="v6main"><header><div><small>CONTROL CENTRAL</small><strong>{client?client.name:view}</strong></div>{canRegister?<button onClick={()=>setModal(true)}>＋ Gesto</button>:<span className="v6contextLabel">{view}</span>}</header>{error&&<div className="v6error">{error}</div>}{client?<Client360 client={client} gestures={data.gestures.filter(g=>g.client_id===client.id)} onBack={()=>setSelected(null)} onNew={()=>setModal(true)}/>:view==='Inicio'?<Home data={data} select={setSelected} go={setView}/>:view==='Clientes'?<Clients data={data} select={setSelected}/>:view==='Gestos'?<Gestures data={data} reload={load}/>:view==='Calendario'?<CalendarWorkspace data={data} month={month} setMonth={setMonth} selected={selected} setSelected={setSelected} onNew={()=>setModal(true)} reload={load}/>:view==='Actividad'?<Activity data={data}/>:<Integrations data={data}/>}</main>{modal&&<NewGesture clients={data.clients} defaultClient={selected||undefined} close={()=>setModal(false)} done={async()=>{setModal(false);await load()}}/>}</div>}

function Home({data,select,go}:{data:Summary;select:(s:string)=>void;go:(v:View)=>void}){return <><section className="v6hero"><small>Centro de Control</small><h1>Operación por cliente</h1><p>Los gestos viven en Supabase y el calendario los refleja por workspace.</p></section><div className="v6metrics"><Metric t="Clientes" v={data.clients.length}/><Metric t="Gestos" v={data.gestures.filter(g=>g.status!=='completed').length}/><Metric t="Calendarios Google" v={data.clients.filter(c=>c.calendar?.status==='connected').length}/></div><div className="v6cols"><Card title="Clientes">{data.clients.map(c=><button className="v6client" key={c.id} onClick={()=>select(c.id)}><b>{c.name}</b><span>{c.gestureCount||0} gestos · {c.calendar?.status==='connected'?'Google conectado':'workspace local'}</span></button>)}</Card><Card title="Próximos gestos"><GestureList gestures={data.gestures.slice(0,8)}/><button className="v6link" onClick={()=>go('Calendario')}>Abrir calendario →</button></Card></div></>}
function Clients({data,select}:{data:Summary;select:(s:string)=>void}){return <><Head t="Clientes" d="Presiona un cliente para abrir su ficha 360."/>{data.clients.map(c=><button className="v6client v6big" key={c.id} onClick={()=>select(c.id)}><b>{c.name}</b><span>{c.stage||'Cliente'} · {c.plan||'Sin plan'} · {c.gestureCount||0} gestos</span></button>)}</>}
function Client360({client,gestures,onBack,onNew}:{client:Client;gestures:Gesture[];onBack:()=>void;onNew:()=>void}){return <><button className="v6link" onClick={onBack}>← Clientes</button><Head t={client.name} d="Ficha 360 del cliente"/><div className="v6metrics"><Metric t="Plan" v={client.plan||'—'}/><Metric t="Valor mensual" v={client.monthlyValue?`$${client.monthlyValue.toLocaleString('es-CL')}`:'—'}/><Metric t="Gestos abiertos" v={gestures.filter(g=>g.status!=='completed').length}/></div><div className="v6cols"><Card title="Estrategia"><p>{client.strategy?.objective||client.strategy?.approach||'Sin estrategia detallada cargada.'}</p><p><b>Próximo hito:</b> {client.cycle?.next_milestone||'—'}</p></Card><Card title="Calendar Workspace"><p><b>{client.calendar?.calendar_name||`${client.name} · Workspace`}</b></p><p>Estado: {client.calendar?.status==='connected'?'Google conectado':'Esperando calendario Google del cliente'}</p><p>Zona horaria: {client.calendar?.timezone||'America/Santiago'}</p><button onClick={onNew}>＋ Registrar gesto</button></Card></div><Card title="Gestos del cliente"><GestureList gestures={gestures}/></Card></>}
function Gestures({data,reload}:{data:Summary;reload:()=>Promise<void>}){return <><Head t="Gestos" d="Trabajo operativo persistente por cliente."/><Card title="Todos los gestos"><GestureList gestures={data.gestures} reload={reload}/></Card></>}

function CalendarWorkspace({data,month,setMonth,selected,setSelected,onNew,reload}:{data:Summary;month:Date;setMonth:(d:Date)=>void;selected:string|null;setSelected:(s:string)=>void;onNew:()=>void;reload:()=>Promise<void>}){const cid=selected||data.clients[0]?.id||'';const[mode,setMode]=useState<CalMode>("Mes");const[focusDay,setFocusDay]=useState(new Date(2026,8,1));const[detail,setDetail]=useState<Occ|null>(null);useEffect(()=>{if(!selected&&cid)setSelected(cid)},[cid,selected,setSelected]);const c=data.clients.find(x=>x.id===cid);const gs=data.gestures.filter(g=>g.client_id===cid);const occ=useMemo(()=>expand(gs,month),[gs,month]);const days=calendarDays(month);const openDay=(d:Date)=>{setFocusDay(d);setMode("Día")};const openOcc=(o:Occ)=>setDetail(o);return <><div className="v6calhead"><div><small>Calendar Workspace</small><h1>Calendario</h1></div><div className="v6calactions"><select value={cid} onChange={e=>setSelected(e.target.value)}>{data.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button onClick={onNew}>＋ Gesto</button></div></div><div className="v6workspaceStatus"><div><b>{c?.calendar?.calendar_name||`${c?.name||'Cliente'} · Workspace`}</b><span>{c?.calendar?.status==='connected'?'Google Calendar conectado':'Workspace Supabase activo · Google pendiente'}</span></div><div><b>{occ.length}</b><span>gestos visibles este mes</span></div></div><div className="v6viewbar">{(["Mes","Día","Año","Lista"] as CalMode[]).map(m=><button className={mode===m?"on":""} onClick={()=>setMode(m)} key={m}>{m}</button>)}</div>{mode==="Mes"&&<><MonthNav month={month} setMonth={setMonth}/><div className="v6gridwrap"><div className="v6week">{['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(d=><b key={d}>{d}</b>)}</div><div className="v6grid">{days.map((d,i)=>{const inMonth=d.getMonth()===month.getMonth();const dos=occ.filter(o=>sameDay(o.date,d));return <div className={`v6day ${inMonth?'':'muted'}`} key={i}><button className="v6daynum" onClick={()=>openDay(d)}>{d.getDate()}</button>{dos.map(o=><button key={o.key} className="v6event" title={o.gesture.title} onClick={()=>openOcc(o)}><i className={o.gesture.sync_status==='synced'?'synced':''}/><em>{o.date.toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'})}</em>{cleanTitle(o.gesture.title)}</button>)}</div>})}</div></div></>}{mode==="Día"&&<DayView day={focusDay} occurrences={occ.filter(o=>sameDay(o.date,focusDay))} setDay={setFocusDay} open={openOcc}/>} {mode==="Año"&&<YearView year={month.getFullYear()} gestures={gs} openMonth={m=>{setMonth(new Date(month.getFullYear(),m,1));setMode("Mes")}}/>}{mode==="Lista"&&<ListView occurrences={occ} open={openOcc}/>}<div className="v6legend"><span>● guardado en app</span><span>● Google sincronizado</span><small>Días y gestos son clickeables.</small></div>{detail?<GestureDetail occ={detail} close={()=>setDetail(null)} reload={reload}/>:null}</>}

function MonthNav({month,setMonth}:{month:Date;setMonth:(d:Date)=>void}){return <div className="v6monthbar"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><b>{new Intl.DateTimeFormat('es-CL',{month:'long',year:'numeric'}).format(month)}</b><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div>}
function DayView({day,occurrences,setDay,open}:{day:Date;occurrences:Occ[];setDay:(d:Date)=>void;open:(o:Occ)=>void}){const move=(n:number)=>{const d=new Date(day);d.setDate(d.getDate()+n);setDay(d)};return <><div className="v6monthbar"><button onClick={()=>move(-1)}>‹</button><b>{new Intl.DateTimeFormat('es-CL',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(day)}</b><button onClick={()=>move(1)}>›</button></div><div className="v6dayAgenda">{occurrences.length?occurrences.map(o=><button className="v6agendaItem" key={o.key} onClick={()=>open(o)}><time>{o.date.toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'})}</time><div><b>{cleanTitle(o.gesture.title)}</b><span>{o.gesture.description||'Sin descripción'}</span></div><em>{o.gesture.sync_status==='synced'?'Google':'App'}</em></button>):<div className="v6empty">No hay gestos este día.</div>}</div></>}
function YearView({year,gestures,openMonth}:{year:number;gestures:Gesture[];openMonth:(m:number)=>void}){return <div className="v6yearGrid">{Array.from({length:12},(_,m)=>{const mm=new Date(year,m,1),count=expand(gestures,mm).length;return <button key={m} onClick={()=>openMonth(m)}><b>{new Intl.DateTimeFormat('es-CL',{month:'long'}).format(mm)}</b><span>{count} gestos</span></button>})}</div>}
function ListView({occurrences,open}:{occurrences:Occ[];open:(o:Occ)=>void}){return <div className="v6listCalendar">{occurrences.length?occurrences.map(o=><button key={o.key} onClick={()=>open(o)}><time>{new Intl.DateTimeFormat('es-CL',{weekday:'short',day:'2-digit',month:'short'}).format(o.date)}<small>{o.date.toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'})}</small></time><div><b>{cleanTitle(o.gesture.title)}</b><span>{o.gesture.description||'Sin descripción'}</span></div><em>{o.gesture.sync_status==='synced'?'Google':'App'}</em></button>):<div className="v6empty">No hay gestos en este mes.</div>}</div>}
function GestureDetail({occ,close,reload}:{occ:Occ;close:()=>void;reload:()=>Promise<void>}){return <div className="v6modal"><div><h2>{cleanTitle(occ.gesture.title)}</h2><p>{new Intl.DateTimeFormat('es-CL',{dateStyle:'full',timeStyle:'short'}).format(occ.date)}</p><p>{occ.gesture.description||'Sin descripción.'}</p><p>Estado: <b>{occ.gesture.status}</b> · Sincronización: <b>{occ.gesture.sync_status}</b></p><footer><button onClick={close}>Cerrar</button><button onClick={async()=>{await toggleComplete(occ.gesture,reload);close()}}>{occ.gesture.status==='completed'?'Reabrir':'Marcar completado'}</button></footer></div></div>}
function GestureList({gestures,reload}:{gestures:Gesture[];reload?:()=>Promise<void>}){return <div className="v6list">{gestures.length?gestures.map(g=><button key={g.id} className="v6row" onClick={()=>reload&&toggleComplete(g,reload)}><div><b>{g.title}</b><span>{new Date(g.starts_at).toLocaleString('es-CL',{dateStyle:'medium',timeStyle:'short'})} · {g.recurrence_rule?'recurrente':'único'}</span></div><em>{g.status==='completed'?'Completado':g.sync_status==='synced'?'Google':'App'}</em></button>):<p>Sin gestos.</p>}</div>}
async function toggleComplete(g:Gesture,reload:()=>Promise<void>){const status=g.status==='completed'?'planned':'completed';await fetch(`/api/gestures/${g.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});await reload()}
function NewGesture({clients,defaultClient,close,done}:{clients:Client[];defaultClient?:string;close:()=>void;done:()=>Promise<void>}){const[clientId,setClientId]=useState(defaultClient||clients[0]?.id||''),[title,setTitle]=useState(''),[startsAt,setStartsAt]=useState('2026-09-01T10:00'),[description,setDescription]=useState(''),[saving,setSaving]=useState(false);async function save(){setSaving(true);const r=await fetch('/api/gestures',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId,title,startsAt,description})});setSaving(false);if(r.ok)await done()}return <div className="v6modal"><div><h2>Registrar gesto</h2><label>Cliente<select value={clientId} onChange={e=>setClientId(e.target.value)}>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Gesto<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ej. Reunión de traspaso"/></label><label>Fecha y hora<input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)}/></label><label>Descripción<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><footer><button onClick={close}>Cancelar</button><button disabled={!title||saving} onClick={save}>{saving?'Guardando…':'Guardar gesto'}</button></footer></div></div>}
function Activity({data}:{data:Summary}){return <><Head t="Actividad" d="Eventos recientes del sistema."/><Card title="Event Bus">{data.recentEvents.map((e:any)=><div className="v6row" key={e.id}><div><b>{e.event_type}</b><span>{e.source_provider}</span></div><em>{new Date(e.received_at).toLocaleString('es-CL')}</em></div>)}</Card></>}
function Integrations({data}:{data:Summary}){return <><Head t="Integraciones" d="Protocolos de conexión, permisos y estado real de cada gateway. Aquí no se registran gestos."/><div className="v6protocolGrid">{data.services.map((s:any)=><section className="v6protocol" key={s.key}><div className="v6protocolHead"><div><small>PROTOCOLO</small><h2>{s.label}</h2></div><span className={s.status==='connected'?'ok':'pending'}>{s.status==='connected'?'Conectado':'Pendiente'}</span></div><p>{s.role}</p><ol>{protocolSteps(s.key).map(step=><li key={step}>{step}</li>)}</ol></section>)}</div><section className="v6card"><h2>Calendarios por cliente</h2>{data.clients.map(c=><div className="v6row" key={c.id}><div><b>{c.name}</b><span>{c.calendar?.calendar_name||`${c.name} · Workspace`} · {c.calendar?.google_calendar_id?'ID Google asignado':'esperando licencia / calendar_id'}</span></div><em>{c.calendar?.status==='connected'?'Conectado':'Pendiente'}</em></div>)}</section></>}
function protocolSteps(key:string){const map:{[k:string]:string[]}={supabase:["Proyecto y credenciales del entorno autorizados","Tablas, RLS y fuente de verdad verificadas","Lectura/escritura con auditoría activa"],twenty:["Workspace y API autorizados","Objetos y campos mapeados a CONTROL CENTRAL","Webhook/eventos y scopes validados"],github:["Repositorio autorizado","Rama y política de cambios definidas","Commits/PR con trazabilidad"],vercel:["Proyecto vinculado al repositorio","Variables de entorno verificadas","Deploy y healthcheck de producción"],chatgpt:["MCP/complemento publicado","Scopes y acciones autorizadas","Prueba end-to-end con Action Registry"]};return map[key]||["Credenciales o licencia autorizada","Scope y permisos definidos","Prueba de lectura/escritura y trazabilidad"]}
function Card({title,children}:{title:string;children:any}){return <section className="v6card"><h2>{title}</h2>{children}</section>}function Head({t,d}:{t:string;d:string}){return <section className="v6hero"><small>Operación</small><h1>{t}</h1><p>{d}</p></section>}function Metric({t,v}:{t:string;v:any}){return <div className="v6metric"><span>{t}</span><b>{v}</b></div>}
function calendarDays(m:Date){const first=new Date(m.getFullYear(),m.getMonth(),1),last=new Date(m.getFullYear(),m.getMonth()+1,0);const start=new Date(first);start.setDate(first.getDate()-((first.getDay()+6)%7));const end=new Date(last);end.setDate(last.getDate()+(7-((last.getDay()+6)%7)-1));const a=[];for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1))a.push(new Date(d));return a}
function expand(gs:Gesture[],m:Date){const start=new Date(m.getFullYear(),m.getMonth(),1),end=new Date(m.getFullYear(),m.getMonth()+1,0,23,59);const out:Occ[]=[];for(const g of gs){const base=new Date(g.starts_at),rule=g.recurrence_rule||'';if(!rule){if(base>=start&&base<=end)out.push({key:g.id,gesture:g,date:base});continue}if(rule.includes('FREQ=WEEKLY')){const by=(rule.match(/BYDAY=([^;]+)/)?.[1]||'').split(',');for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){if(by.some(x=>DAYMAP[x]===d.getDay())&&d>=new Date(base.getFullYear(),base.getMonth(),base.getDate())){const x=new Date(d);x.setHours(base.getHours(),base.getMinutes(),0,0);out.push({key:`${g.id}-${x.toISOString()}`,gesture:g,date:x})}}}else if(rule.includes('BYMONTHDAY=1')){const x=new Date(m.getFullYear(),m.getMonth(),1,base.getHours(),base.getMinutes());if(x>=base)out.push({key:`${g.id}-${x.toISOString()}`,gesture:g,date:x})}else if(rule.includes('BYDAY=-1FR')){const x=new Date(m.getFullYear(),m.getMonth()+1,0,base.getHours(),base.getMinutes());while(x.getDay()!==5)x.setDate(x.getDate()-1);if(x>=base)out.push({key:`${g.id}-${x.toISOString()}`,gesture:g,date:x})}}return out.sort((a,b)=>a.date.getTime()-b.date.getTime())}
function sameDay(a:Date,b:Date){return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}function cleanTitle(t:string){return t.replace(/^[^·]+·\s*/,"")}
