"use client";

import {useEffect,useMemo,useState} from "react";

type Client={id:string;name:string};

export default function TaskActionBridge(){
 const [open,setOpen]=useState(false),[clients,setClients]=useState<Client[]>([]),[clientId,setClientId]=useState(""),[title,setTitle]=useState(""),[date,setDate]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[priority,setPriority]=useState("2"),[money,setMoney]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const planned=useMemo(()=>{if(!date||!start||!end)return 30;const a=new Date(`${date}T${start}`),b=new Date(`${date}T${end}`);return Math.max(1,Math.round((b.getTime()-a.getTime())/60000))},[date,start,end]);
 useEffect(()=>{
  const today=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Santiago",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());setDate(today);
  fetch("/api/system-summary",{cache:"no-store"}).then(r=>r.json()).then(j=>{const cs=(j.clients||[]).map((c:any)=>({id:c.id,name:c.name}));setClients(cs);if(cs[0])setClientId(cs[0].id)}).catch(()=>{});
  const show=(event:Event)=>{const detail=(event as CustomEvent<{clientId?:string;date?:string}>).detail||{};if(detail.clientId!==undefined)setClientId(detail.clientId);if(detail.date)setDate(detail.date);setError("");setOpen(true)};
  window.addEventListener("cc-new-task",show);return()=>window.removeEventListener("cc-new-task",show);
 },[]);
 async function save(){
  setError("");if(!title.trim()||!date||!start||!end){setError("Completa título, fecha, inicio y finalización.");return}if(new Date(`${date}T${end}`)<=new Date(`${date}T${start}`)){setError("La hora de finalización debe ser posterior al inicio.");return}
 setSaving(true);try{const r=await fetch("/api/work",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"create",title:title.trim(),clientId:clientId||null,startsAt:new Date(`${date}T${start}`).toISOString(),endsAt:new Date(`${date}T${end}`).toISOString(),plannedMinutes:planned,priority:Number(priority),isMoney:money,source:"control_central"})});const j=await r.json();if(!r.ok)throw new Error(j.error||"No se pudo crear la tarea");setOpen(false);setTitle("");setStart("");setEnd("");setMoney(false);window.dispatchEvent(new Event("cc-work-changed"));window.location.reload()}catch(e:unknown){setError(e instanceof Error?e.message:"No se pudo crear la tarea")}finally{setSaving(false)}
 }
 if(!open)return null;
 return <div className="task-bridge-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="task-bridge-modal" role="dialog" aria-modal="true" aria-label="Nueva tarea"><header><div><small>NUEVA TAREA</small><h2>Programar trabajo</h2></div><button onClick={()=>setOpen(false)} aria-label="Cerrar">×</button></header><label>Proyecto / cliente<select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Personal</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Tarea<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="Qué debe quedar cerrado"/></label><div className="task-bridge-grid"><label>Fecha<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Inicio<input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Final<input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><div className="task-bridge-grid two"><label>Prioridad<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="1">Alta</option><option value="2">Media</option><option value="3">Baja</option></select></label><label className="task-bridge-money"><input type="checkbox" checked={money} onChange={e=>setMoney(e.target.checked)}/> Movimiento comercial</label></div><div className="task-bridge-duration">Bloque planificado: <b>{planned} min</b></div>{error&&<p className="task-bridge-error">{error}</p>}<button className="task-bridge-save" disabled={saving} onClick={save}>{saving?"Guardando…":"Crear tarea"}</button><style>{css}</style></section></div>
}
const css=`.task-bridge-backdrop{position:fixed;inset:0;z-index:10000;background:rgba(16,18,17,.42);backdrop-filter:blur(5px);display:grid;place-items:center;padding:18px}.task-bridge-modal{width:min(560px,100%);background:var(--link-surface,#fff);color:var(--link-text,#1c201e);border:1px solid var(--link-line,#d8d9d5);border-radius:20px;padding:22px;box-shadow:0 28px 90px rgba(0,0,0,.2)}.task-bridge-modal header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:18px}.task-bridge-modal header small{font-size:9px;letter-spacing:.2em;color:var(--link-muted,#777)}.task-bridge-modal h2{margin:5px 0 0;font-size:24px}.task-bridge-modal header button{border:1px solid var(--link-line,#ddd);background:var(--link-surface-2,#f4f4f1);color:inherit;width:34px;height:34px;border-radius:10px;font-size:20px}.task-bridge-modal label{display:flex;flex-direction:column;gap:6px;font-size:11px;margin:10px 0}.task-bridge-modal input,.task-bridge-modal select{width:100%;border:1px solid var(--link-line,#ddd);background:var(--link-surface-2,#f7f7f4);color:inherit;border-radius:10px;padding:11px;font:inherit}.task-bridge-grid{display:grid;grid-template-columns:1.2fr 1fr 1fr;gap:9px}.task-bridge-grid.two{grid-template-columns:1fr 1fr;align-items:end}.task-bridge-money{flex-direction:row!important;align-items:center!important;border:1px solid var(--link-line,#ddd);border-radius:10px;padding:11px}.task-bridge-money input{width:auto}.task-bridge-duration{font-size:11px;color:var(--link-muted,#777);padding:8px 0}.task-bridge-error{font-size:11px;color:#c94c46}.task-bridge-save{width:100%;border:0;border-radius:11px;background:var(--link-accent,#18211f);color:var(--link-accent-text,#fff);padding:13px;font-weight:700;margin-top:7px}@media(max-width:620px){.task-bridge-modal{padding:17px;border-radius:17px}.task-bridge-grid,.task-bridge-grid.two{grid-template-columns:1fr 1fr}.task-bridge-grid label:first-child{grid-column:1/-1}}`;
